#!/usr/bin/env python

import smsn
import argparse
import os
import sys
import logging

def main():

    parser = argparse.ArgumentParser()

    def check_positive(value):
        ivalue = int(value)
        if ivalue <= 0:
            raise argparse.ArgumentTypeError("%s is an invalid positive int value" % value)
        return ivalue

    parser.add_argument("--modelCSV","-m",
                            help='Path to a .csv of ipdModels generated by ipdtools',
                            required=True)

    parser.add_argument("--bam","-b",
                            help="Path to a .bam file with all the subreads",
                            required=True
                        )

    parser.add_argument("--reference","-r",
                            help='Path to a genome reference (fasta file).',
                            required=True,
                            default=None)

    parser.add_argument('--output_csv',"-o",
                            help='Ouput file (csv) of the methylation analysis. See the README for further details on the output\'s format.',
                            required=True)

    parser.add_argument('--verbosity',"-v",
                            help='Choose your verbosity. Default: INFO',
                            required=False,
                            default="INFO",
                            choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"])

    parser.add_argument('--progress_bar',"-p",
                            help='Displays a progress bar',
                            required=False,
                            action='store_true')

    parser.add_argument('--nproc','-n',
                        help="Max number of processors for parallelism. DEFAULT: 1, positive integers only. Rq: The programm will actually use n+1 >= 2 CPU no matter what.",
                        required=False,
                        default=1,
                        type=check_positive)

    args = parser.parse_args()

    fastafile = os.path.realpath(args.fastafile)
    bamfile = os.path.realpath(args.bam)
    output_csv = os.path.realpath(args.output_csv)

    verboselevel = "logging."+str(args.verbosity)
    logging.basicConfig(level=eval(verboselevel),
                        format='%(asctime)s %(message)s',
                        stream=sys.stdout)


    show_progress_bar = False
    if args.progress_bar:
        show_progress_bar = True

    logging.critical("[CRITICAL] Not implemented")
    # ipdtools.ipdModel.compute_fasta_to_csv(modelname=args.model, fastafile=fastafile, csv_out=output_csv,
    #                                        show_progress_bar=show_progress_bar,nproc=args.nproc,indexing=args.indexing)

if __name__ == "__main__":
    main()
